name: lolipop

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ssh key generate
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - name: deploy
      working-directory: ./app/laravel
      run: |
        composer validate
        composer install -n --prefer-dist
        rsync -auvz -e "ssh -o 'StrictHostKeyChecking no' -i ~/.ssh/id_rsa -p ${{ secrets.SSH_PORT }}" ./ ${{ secrets.SSH_ACCOUNT }}@${{ secrets.SSH_SERVER }}:/home/users/2/path/to/lomo.jp-nosuke-0511
