# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: npm install        # パッケージをインストール
      run: npm install
    - name: test
      run: npm run test:unit   # unitテストを実行
    - name: build              # ビルド
      run: npm run build --if-present

    - name: List output files
      run: ls                           # ファイルリストを表示

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0   # FTPを使ってサーバーにDeployするアクションを実行
      
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}     # FTPサーバーのURLを設定
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }} # FTPのユーザー名を設定
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }} # FTPのパスワードを設定
        LOCAL_DIR: dist                           # どのディレクトリのデータをアップロードするか
        REMOTE_DIR: /nosukeportfolio.xyz/self-introduction-app      # ロリポップFTPサーバのどのディレクトリにアップロードするか
        ARGS: --delete
